#### The following implementation of the perceptron uses the numerical definition of the derivative for the gradient descent algorithm. A small value of epsilon was used to iterate between the W weights, since the Ws are the values we want to optimize in the cost function:

 \begin{align}
 \frac{f(x+\varepsilon )-f(x)}{\varepsilon }
 \end{align}

#### W's are updated using the following formula:

\begin{align}
W_{i+1}=W_i - \eta \frac{\partial J}{\partial W_i} 
\end{align}

#### The J-cost function is determined by:
 \begin{align}
(y-\hat{y})^2
\end{align}
#### where $y$ is the actual value and $ \hat{y} $ is the predicted value.

In [1]:
import numpy as np

### We are going to create 2 functions
1.- The **outputFunction**: which is performed by the dot product between the **X** inputs and the **W** weights

2.- The **transferFunction**: which will use the logistics function


In [2]:
def outputFunction(weights, inputs):
    return np.dot(weights, inputs)


def transferFunction(activation):
    return 1.0 / (1.0 + np.exp(-activation))

In [3]:
input_dim = 2 #Number of neurons
learning_rate = 0.1 #eta learning rate for the gradient descent
numIte=2000 # number of iterations for learning, epoch
eps = 1e-4 #epsilon for the numerical derivative

#### We assign the weights for the AND gate

In [4]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) #Our input X
y = np.array([0, 0, 0, 1]) #Our output Y


#### We integrate the bias as one more input to the set of X with a value of 1 and add a W for the additional bias

In [5]:
W = np.random.rand(input_dim + 1) #we generate random values for the weights
bias = np.ones((np.size(X,0),1)) 

X = np.concatenate((X, bias), axis=1)
training_count = np.size(X,0)
X


array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [6]:

W_Delta = np.array(W)
NewW = np.array(W)


In [7]:
print(W) #First Weights
print('__________________')
print(transferFunction(outputFunction(X, W))) #First Output

[0.96293906 0.71011711 0.44880677]
__________________
[0.61035549 0.76113712 0.80404116 0.89301005]


In [8]:
for i in range(0, numIte):

    for j in range(0, training_count):
        pred = transferFunction(outputFunction(X[j, :], W))
        error=(y[j]-pred)**2
        print(f'{j} {error}')
        for k in range(0, np.size(W)):
            W_Delta = np.array(W)
            W_Delta[k] = W_Delta[k] + eps #The epsilon is iterated between the W
            
            #The output, yHat & yHatDelta is calculated using the W and the W+epsilon
            yHat = transferFunction(outputFunction(X[j, :], W))
            yHatDelta = transferFunction(outputFunction(X[j, :], W_Delta)) 

            errorDerivado_delta = (y[j] - yHatDelta)**2
            errorDerivado = (y[j] - yHat)**2
            NewW[k] = W[k] - learning_rate * (((errorDerivado_delta) - (errorDerivado)) / eps) 
        print(f'**********')
        W = NewW
    print('__________________')



0 0.3725338302465621
**********
1 0.5712624469451082
**********
2 0.6318387918382184
**********
3 0.01459618284372825
**********
__________________
0 0.3492648638558878
**********
1 0.5414005158825956
**********
2 0.6042726263529151
**********
3 0.018384903973407415
**********
__________________
0 0.3262570329135677
**********
1 0.5107178102044584
**********
2 0.5755568588822331
**********
3 0.023075417338306755
**********
__________________
0 0.30377208888660845
**********
1 0.479647425666305
**********
2 0.5460438306632674
**********
3 0.028791160746235184
**********
__________________
0 0.2820650590151651
**********
1 0.4486755817386684
**********
2 0.5161550136482358
**********
3 0.035625111099478565
**********
__________________
0 0.2613664590690564
**********
1 0.4183052569875815
**********
2 0.48635338647442944
**********
3 0.04362046733318465
**********
__________________
0 0.24186615929144964
**********
1 0.389014060321223
**********
2 0.4571071479833401
**********
3 0.0527550

In [9]:
print(W) #Final Weights
print('__________________')
print(transferFunction(outputFunction(X, W))) #Final Output

[ 4.39626429  4.39076919 -6.68686063]
__________________
[0.00124564 0.09144718 0.09190477 0.89091998]
